export interface Floorplan {
  title: string;
  rooms: string;
  surface: string;
  description: string;
}

export interface Development {
  id: string;
  name: string;
  location: string;
  zone: 'tres-de-febrero' | 'moron' | 'nordelta' | 'otras-zonas';
  zoneDisplay: string;
  neighborhood: string;
  status: 'en-progreso' | 'obra-finalizada';
  units: string;
  unitTypes: number[]; // e.g. [1, 2] for 1 and 2 rooms
  advanceAndInstallments: string;
  cuotasCount: number;
  deliveryDate: string;
  deliveryYear: number;
  isSoldOut?: boolean;
  isLastUnits?: boolean;
  isFeatured?: boolean;
  isOffice?: boolean;
  priceFromUSD: number;
  image: string;
  gallery: string[];
  brochureUrl?: string;
  description: string;
  features: string[];
  floorplans?: Floorplan[];
  address: string;
}

export const ALL_DEVELOPMENTS: Development[] = [
  // --- TRES DE FEBRERO ---
  {
    id: 'andres-ferreyra-2930',
    name: 'Andrés Ferreyra 2930',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Andrés Ferreyra 2930, Caseros',
    status: 'en-progreso',
    units: 'Unidades de 1 y 2 Ambientes',
    unitTypes: [1, 2],
    advanceAndInstallments: 'Adelanto del 50% + 18 cuotas fijas',
    cuotasCount: 18,
    deliveryDate: 'Entrega en Diciembre 2028',
    deliveryYear: 2028,
    isFeatured: true,
    priceFromUSD: 44000,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg', '/images/building_balconies.jpg', '/images/building_brick.jpg'],
    description: 'Emprendimiento residencial de vanguardia en la mejor zona de Caseros. Unidades luminosas con amplios balcones, terminaciones de categoría y cocheras opcionales.',
    features: ['Balcones con parrilla', 'Cocheras cubiertas', 'Pisos de porcelanato', 'Aberturas DVH', 'Ascensor digital', 'Grifería FV'],
    floorplans: [
      { title: 'Monoambiente Divisible', rooms: '1 Ambiente', surface: '36 m²', description: 'Cocina integrada con mesada de granito, baño completo y balcón al frente.' },
      { title: '2 Ambientes con Balcón', rooms: '2 Ambientes', surface: '52 m²', description: 'Dormitorio con placard, living comedor amplio y ventilación cruzada.' }
    ]
  },
  {
    id: 'jose-m-bosch-1394',
    name: 'Jose M Bosch 1394',
    location: 'Villa Bosch',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Villa Bosch, Tres de Febrero',
    neighborhood: 'Villa Bosch',
    address: 'José María Bosch 1394, Villa Bosch',
    status: 'en-progreso',
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 24 cuotas fijas',
    cuotasCount: 24,
    deliveryDate: 'Entrega en Septiembre 2028',
    deliveryYear: 2028,
    isFeatured: true,
    priceFromUSD: 52000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg', '/images/building_corner.jpg', '/images/building_caseros.jpg'],
    description: 'Ubicación privilegiada en pleno centro comercial y residencial de Villa Bosch. Próximo a la estación del FFCC Urquiza y avenidas principales.',
    features: ['SUM y terraza equipada', 'Preinstalación de A/A', 'Cocina con bajomesada', 'Ascensores de última generación'],
    floorplans: [
      { title: '1 Ambiente Funcional', rooms: '1 Ambiente', surface: '34 m²', description: 'Optimizado para maximizar la luz solar, baño completo y cocina americana.' },
      { title: '3 Ambientes Familiar', rooms: '3 Ambientes', surface: '74 m²', description: 'Suite principal con vestidor, segundo dormitorio con placard y balcón terraza.' }
    ]
  },
  {
    id: 'melian-7912',
    name: 'Melián 7912',
    location: 'Martín Coronado',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Martín Coronado, Tres de Febrero',
    neighborhood: 'Martín Coronado',
    address: 'Melián 7912, Martín Coronado',
    status: 'en-progreso',
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 24 cuotas fijas',
    cuotasCount: 24,
    deliveryDate: 'Entrega en Septiembre 2028',
    deliveryYear: 2028,
    priceFromUSD: 49000,
    image: '/images/building_brick.jpg',
    gallery: ['/images/building_brick.jpg', '/images/building_caseros.jpg'],
    description: 'Diseño arquitectónico moderno en entorno residencial arbolado y tranquilo de Martín Coronado. Financiación flexible.',
    features: ['Seguridad con cámaras', 'Solárium en azotea', 'Excelente luz natural', 'Bajas expensas']
  },
  {
    id: 'belgrano-4454',
    name: 'Belgrano 4454',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Av. Belgrano 4454, Caseros',
    status: 'en-progreso',
    units: 'Unidades de 1 Ambiente',
    unitTypes: [1],
    advanceAndInstallments: 'Adelanto del 50% + 18 cuotas fijas',
    cuotasCount: 18,
    deliveryDate: 'Entrega en Agosto 2028',
    deliveryYear: 2028,
    priceFromUSD: 39500,
    image: '/images/building_corner.jpg',
    gallery: ['/images/building_corner.jpg', '/images/building_balconies.jpg'],
    description: 'Monoambientes divisibles ideales para inversión o primera vivienda con alta rentabilidad de alquiler tradicional y temporario.',
    features: ['Apto profesional', 'Bajo costo de mantenimiento', 'Griferías FV', 'Muebles de diseño']
  },
  {
    id: 'urquiza-4550',
    name: 'Urquiza 4550',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Urquiza 4550, Caseros',
    status: 'en-progreso',
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 26 cuotas fijas',
    cuotasCount: 26,
    deliveryDate: 'Entrega en Noviembre 2028',
    deliveryYear: 2028,
    isFeatured: true,
    priceFromUSD: 46000,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg', '/images/building_moron.jpg'],
    description: 'Gran torre con amenities en el corazón neurálgico de Caseros. Unidades espaciosas con óptima distribución.',
    features: ['Salón de usos múltiples', 'Laundry comunitario', 'Cocheras disponibles', 'Rampa de accesibilidad']
  },
  {
    id: 'hornos-2719',
    name: 'Hornos 2719',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Hornos 2719, Caseros',
    status: 'en-progreso',
    isLastUnits: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Contado',
    cuotasCount: 0,
    deliveryDate: 'Entrega en Octubre 2026',
    deliveryYear: 2026,
    isFeatured: true,
    priceFromUSD: 55000,
    image: '/images/building_moron.jpg',
    gallery: ['/images/building_moron.jpg', '/images/building_brick.jpg'],
    description: 'Emprendimiento en etapa avanzada de obra. Últimas unidades con entrega rápida garantizada.',
    features: ['Últimas unidades', 'Etapa avanzada', 'Terminaciones prémium', 'Visita a obra disponible']
  },
  {
    id: 'belgrano-4664',
    name: 'Belgrano 4664',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Belgrano 4664, Caseros',
    status: 'en-progreso',
    isLastUnits: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 13 cuotas fijas',
    cuotasCount: 13,
    deliveryDate: 'Entrega en Octubre 2027',
    deliveryYear: 2027,
    priceFromUSD: 48000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg', '/images/building_corner.jpg'],
    description: 'Excelente desarrollo sobre la emblemática calle Belgrano. Balcones aterrazados y finas terminaciones.',
    features: ['Últimas unidades', 'Balcones aterrazados', 'Parrillas individuales', 'Cocheras optativas']
  },
  {
    id: 'valentin-gomez-4736',
    name: 'Valentín Gómez 4736/44',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Valentín Gómez 4736, Caseros',
    status: 'en-progreso',
    isLastUnits: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 15 cuotas fijas',
    cuotasCount: 15,
    deliveryDate: 'Entrega en Diciembre 2027',
    deliveryYear: 2027,
    priceFromUSD: 47000,
    image: '/images/building_brick.jpg',
    gallery: ['/images/building_brick.jpg', '/images/building_caseros.jpg'],
    description: 'Desarrollo moderno sobre Valentín Gómez, conectividad inmejorable con autopistas y transporte público.',
    features: ['Edificio sustentable', 'Luminarias LED', 'Termotanques de alta eficiencia', 'Cocheras fijas']
  },
  {
    id: 'las-malvinas-7254',
    name: 'Las Malvinas 7254',
    location: 'Martín Coronado',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Martín Coronado, Tres de Febrero',
    neighborhood: 'Martín Coronado',
    address: 'Las Malvinas 7254, Martín Coronado',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Enero 2026',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Enero 2026',
    deliveryYear: 2026,
    priceFromUSD: 60000,
    image: '/images/building_corner.jpg',
    gallery: ['/images/building_corner.jpg'],
    description: 'Obra 100% terminada y entregada en los plazos fijados por Clamaco Constructora. Casos de éxito comprobados.',
    features: ['100% Entregado', 'Familias ya viviendo', 'Calidad certificada']
  },
  {
    id: 'nuestra-sra-merced-4770',
    name: 'Nuestra Sra. de la Merced 4770',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'Nuestra Sra. de la Merced 4770, Caseros',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Enero 2025',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Enero 2025',
    deliveryYear: 2025,
    priceFromUSD: 58000,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg'],
    description: 'Emprendimiento residencial consolidado en Caseros. Alta revalorización obtenida por los inversores.',
    features: ['100% Entregado', 'Rentabilidad comprobada', 'Diseño vanguardista']
  },
  {
    id: 'david-magdalena-2734',
    name: 'David Magdalena 2734',
    location: 'Caseros',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Caseros, Tres de Febrero',
    neighborhood: 'Caseros',
    address: 'David Magdalena 2734, Caseros',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Marzo 2025',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Marzo 2025',
    deliveryYear: 2025,
    priceFromUSD: 59000,
    image: '/images/building_moron.jpg',
    gallery: ['/images/building_moron.jpg'],
    description: 'Edificio de gran presencia urbana entregado exitosamente. Clamaco & Di Paolo garantía de cumplimiento.',
    features: ['100% Entregado', 'Ubicación premium', 'Clientes satisfechos']
  },
  {
    id: 'america-347',
    name: 'América 347',
    location: 'Saenz Peña',
    zone: 'tres-de-febrero',
    zoneDisplay: 'Saenz Peña, Tres de Febrero',
    neighborhood: 'Sáenz Peña',
    address: 'América 347, Sáenz Peña',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Octubre 2023',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Octubre 2023',
    deliveryYear: 2023,
    priceFromUSD: 62000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg'],
    description: 'En el límite con Villa Devoto (CABA). Proyecto culminado con gran éxito y fidelización de propietarios.',
    features: ['100% Entregado', 'A metros de CABA', 'Constructora Clamaco']
  },

  // --- OTRAS ZONAS / MORÓN / NORDELTA ---
  {
    id: 'uruguay-518',
    name: 'Uruguay 518',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Uruguay 518, Morón Centro',
    status: 'en-progreso',
    units: 'Unidades de 1 y 2 Ambientes',
    unitTypes: [1, 2],
    advanceAndInstallments: 'Adelanto del 50% + 15 cuotas fijas',
    cuotasCount: 15,
    deliveryDate: 'Entrega en Julio 2028',
    deliveryYear: 2028,
    isFeatured: true,
    priceFromUSD: 46000,
    image: '/images/building_moron.jpg',
    gallery: ['/images/building_moron.jpg', '/images/building_corner.jpg'],
    description: 'Ubicado en la zona céntrica más cotizada de Morón, con acceso directo al tren Sarmiento y zona bancaria.',
    features: ['Balcones aterrazados', 'Pisos flotantes y porcelanato', 'Ascensor con cabina de acero inoxidable']
  },
  {
    id: 'mitre-540',
    name: 'Mitre 540',
    location: 'Ramos Mejía',
    zone: 'otras-zonas',
    zoneDisplay: 'Ramos Mejía',
    neighborhood: 'Ramos Mejía',
    address: 'Bartolomé Mitre 540, Ramos Mejía',
    status: 'en-progreso',
    units: 'Unidades de 2 y 3 Ambientes',
    unitTypes: [2, 3],
    advanceAndInstallments: 'Adelanto del 50% + 15 cuotas fijas',
    cuotasCount: 15,
    deliveryDate: 'Entrega en Enero 2027',
    deliveryYear: 2027,
    priceFromUSD: 68000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg', '/images/building_caseros.jpg'],
    description: 'Zona residencial exclusiva en Ramos Mejía. Semipisos de alta gama con terminaciones de primer nivel.',
    features: ['Semipisos exclusivos', 'Cocheras cubiertas', 'Parrillas individuales', 'Cámara de seguridad']
  },
  {
    id: 'gral-bustillo-357',
    name: 'Gral. Bustillo 357',
    location: 'Castelar',
    zone: 'otras-zonas',
    zoneDisplay: 'Castelar',
    neighborhood: 'Castelar',
    address: 'Gral. Bustillo 357, Castelar',
    status: 'en-progreso',
    units: 'Unidades de 1 y 2 Ambientes',
    unitTypes: [1, 2],
    advanceAndInstallments: 'Adelanto del 50% + 11 cuotas fijas',
    cuotasCount: 11,
    deliveryDate: 'Entrega en Septiembre 2028',
    deliveryYear: 2028,
    priceFromUSD: 49500,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg'],
    description: 'En el barrio más arbolado y distinguido de la zona oeste. Ideal para vivir con confort y tranquilidad.',
    features: ['Entorno verde', 'Calefacción por radiadores', 'Amplios ventanales']
  },
  {
    id: 'mitre-929',
    name: 'Mitre 929',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Mitre 929, Morón Centro',
    status: 'obra-finalizada',
    isLastUnits: true,
    units: 'Unidades de 1 Ambiente',
    unitTypes: [1],
    advanceAndInstallments: 'Contado',
    cuotasCount: 0,
    deliveryDate: 'Entrega inmediata',
    deliveryYear: 2026,
    priceFromUSD: 41000,
    image: '/images/building_brick.jpg',
    gallery: ['/images/building_brick.jpg'],
    description: 'Obra concluida con entrega de llaves inmediata. Excelente opción para renta inmediata.',
    features: ['Últimas unidades', 'Entrega inmediata', 'Listo para habitar']
  },
  {
    id: 'yatay-754',
    name: 'Yatay 754',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Yatay 754, Morón Centro',
    status: 'en-progreso',
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Contado',
    cuotasCount: 0,
    deliveryDate: 'Entrega en Noviembre 2028',
    deliveryYear: 2028,
    priceFromUSD: 51000,
    image: '/images/building_corner.jpg',
    gallery: ['/images/building_corner.jpg'],
    description: 'Gran torre en construcción en Morón Centro con amenities y cocheras en subsuelo.',
    features: ['Solárium y terraza', 'Salón de eventos', 'Diseño bioclimático']
  },
  {
    id: 'virasoro-325',
    name: 'Virasoro 325',
    location: 'Palomar',
    zone: 'otras-zonas',
    zoneDisplay: 'Palomar',
    neighborhood: 'Palomar',
    address: 'Virasoro 325, El Palomar',
    status: 'en-progreso',
    units: 'Unidades de 2 Ambientes',
    unitTypes: [2],
    advanceAndInstallments: 'Contado',
    cuotasCount: 0,
    deliveryDate: 'Entrega en Septiembre 2026',
    deliveryYear: 2026,
    priceFromUSD: 48000,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg'],
    description: 'Desarrollo en Palomar con entrega en 2026. Excelente conectividad con aeroparque Palomar y tren San Martín.',
    features: ['Cocina equipada', 'Espacios luminosos', 'Precios de oportunidad']
  },
  {
    id: 'oficinas-av-roca-1276',
    name: 'Oficinas Av. Roca 1276',
    location: 'Hurlingham',
    zone: 'otras-zonas',
    zoneDisplay: 'Hurlingham',
    neighborhood: 'Hurlingham',
    address: 'Av. Roca 1276, Hurlingham',
    status: 'obra-finalizada',
    isLastUnits: true,
    isOffice: true,
    units: 'Oficinas de 1, 2 ambientes y semipisos',
    unitTypes: [1, 2],
    advanceAndInstallments: 'Contado',
    cuotasCount: 0,
    deliveryDate: 'Entrega inmediata',
    deliveryYear: 2026,
    priceFromUSD: 38000,
    image: '/images/building_moron.jpg',
    gallery: ['/images/building_moron.jpg'],
    description: 'Edificio corporativo de vanguardia sobre avenida principal en Hurlingham. Oficinas y semipisos profesionales.',
    features: ['Últimas unidades', 'Apto corporativo', 'Seguridad y control de acceso', 'Entrega inmediata']
  },
  {
    id: 'torres-zafiro',
    name: 'Torres Zafiro',
    location: 'Nordelta',
    zone: 'nordelta',
    zoneDisplay: 'Nordelta',
    neighborhood: 'Nordelta',
    address: 'Boulevard del Mirador, Nordelta',
    status: 'en-progreso',
    isLastUnits: true,
    isFeatured: true,
    units: 'Unidades de 2, 3 y 4 Ambientes',
    unitTypes: [2, 3, 4],
    advanceAndInstallments: 'Adelanto del 50% + 12 cuotas fijas',
    cuotasCount: 12,
    deliveryDate: 'Entrega en Diciembre 2027',
    deliveryYear: 2027,
    priceFromUSD: 115000,
    image: '/images/building_nordelta.jpg',
    gallery: ['/images/building_nordelta.jpg', '/images/building_balconies.jpg'],
    description: 'Complejo residencial premium en Nordelta con vistas a laguna, piscinas, gimnasio, spa y marina náutica.',
    features: ['Últimas unidades', 'Vistas al agua', 'Piscina infinity', 'Seguridad 24hs', 'Cocheras dobles']
  },
  {
    id: 'santa-fe-652',
    name: 'Santa Fe 652',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Santa Fe 652, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Enero 2025',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Enero 2025',
    deliveryYear: 2025,
    priceFromUSD: 54000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg'],
    description: 'Emprendimiento terminado y entregado exitosamente a sus propietarios en Morón Centro.',
    features: ['100% Entregado', 'Construcción Clamaco', 'Calidad comprobada']
  },
  {
    id: 'mitre-1185',
    name: 'Mitre 1185',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Mitre 1185, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Enero 2026',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Enero 2026',
    deliveryYear: 2026,
    priceFromUSD: 56000,
    image: '/images/building_brick.jpg',
    gallery: ['/images/building_brick.jpg'],
    description: 'Emprendimiento exitoso sobre calle Mitre en Morón. Excelente valorización.',
    features: ['100% Entregado', 'Totalmente comercializado']
  },
  {
    id: 'san-martin-861',
    name: 'San Martín 861',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'San Martín 861, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Julio 2024',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Julio 2024',
    deliveryYear: 2024,
    priceFromUSD: 53000,
    image: '/images/building_caseros.jpg',
    gallery: ['/images/building_caseros.jpg'],
    description: 'Edificio entregado en tiempo récord con altos estándares de calidad.',
    features: ['100% Entregado', 'Garantía cumplida']
  },
  {
    id: '25-de-mayo-743',
    name: '25 de Mayo 743',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: '25 de Mayo 743, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1 ambiente',
    unitTypes: [1],
    advanceAndInstallments: 'Entregado en Junio 2024',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Junio 2024',
    deliveryYear: 2024,
    priceFromUSD: 42000,
    image: '/images/building_corner.jpg',
    gallery: ['/images/building_corner.jpg'],
    description: 'Edificio de monoambientes premium completamente entregado a sus inversores.',
    features: ['100% Entregado', 'Alta rentabilidad de alquiler']
  },
  {
    id: 'machado-1120',
    name: 'Machado 1120',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Machado 1120, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 1, 2 y 3 Ambientes',
    unitTypes: [1, 2, 3],
    advanceAndInstallments: 'Entregado en Marzo 2023',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Marzo 2023',
    deliveryYear: 2023,
    priceFromUSD: 51000,
    image: '/images/building_moron.jpg',
    gallery: ['/images/building_moron.jpg'],
    description: 'Emprendimiento terminado y habitado en Morón con excelente satisfacción.',
    features: ['100% Entregado', 'Familias satisfechas']
  },
  {
    id: 'torres-cristal',
    name: 'Torres Cristal',
    location: 'Nordelta',
    zone: 'nordelta',
    zoneDisplay: 'Nordelta',
    neighborhood: 'Nordelta',
    address: 'Avenida del Puerto, Nordelta',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 2, 3 y 4 Ambientes',
    unitTypes: [2, 3, 4],
    advanceAndInstallments: 'Entregado en Septiembre 2023',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Septiembre 2023',
    deliveryYear: 2023,
    priceFromUSD: 125000,
    image: '/images/building_nordelta.jpg',
    gallery: ['/images/building_nordelta.jpg'],
    description: 'Prestigioso complejo náutico en Nordelta totalmente culminado y entregado.',
    features: ['100% Entregado', 'Nordelta Premium', 'Gran plusvalía']
  },
  {
    id: 'moreno-762',
    name: 'Moreno 762',
    location: 'Morón Centro',
    zone: 'moron',
    zoneDisplay: 'Morón Centro',
    neighborhood: 'Morón Centro',
    address: 'Moreno 762, Morón',
    status: 'obra-finalizada',
    isSoldOut: true,
    units: 'Unidades de 2 Ambientes',
    unitTypes: [2],
    advanceAndInstallments: 'Entregado en Diciembre 2023',
    cuotasCount: 0,
    deliveryDate: 'Entregado en Diciembre 2023',
    deliveryYear: 2023,
    priceFromUSD: 57000,
    image: '/images/building_balconies.jpg',
    gallery: ['/images/building_balconies.jpg'],
    description: 'Edificio residencial en Morón Centro culminado con éxito rotundo.',
    features: ['100% Entregado', 'Calidad Clamaco']
  }
];

export const DEVELOPMENTS_TRES_DE_FEBRERO = ALL_DEVELOPMENTS.filter(
  (d) => d.zone === 'tres-de-febrero'
);

export const DEVELOPMENTS_OTRAS_ZONAS = ALL_DEVELOPMENTS.filter(
  (d) => d.zone !== 'tres-de-febrero'
);

export function getDevelopmentById(id: string): Development | undefined {
  return ALL_DEVELOPMENTS.find((d) => d.id === id);
}

export function getFeaturedDevelopments(): Development[] {
  return ALL_DEVELOPMENTS.filter((d) => d.isFeatured);
}

export const GOOGLE_REVIEWS = [
  {
    id: '1',
    author: 'Silvina Medrano',
    rating: 5,
    text: 'Fueron muy amables en la atención, pacientes xa responder todas mis consultas y resolutivos al momento de conciliar los números. Gracias!!!!',
    avatar: 'SM',
    time: 'Hace 2 semanas',
    avatarBg: 'bg-emerald-600'
  },
  {
    id: '2',
    author: 'Horacio Olmos',
    rating: 5,
    text: 'Fue una experiencia comercial con dificultades al principio, pero el resultado final fue excelente y cambió mi perspectiva por completo. Muy profesionales.',
    avatar: 'HO',
    time: 'Hace 1 mes',
    avatarBg: 'bg-blue-600'
  },
  {
    id: '3',
    author: 'Pablo Ramírez',
    rating: 5,
    text: 'Súper recomendables! Excelente atención, acompañamiento durante toda la operación y buen trato. Mención especial para Leo que es un genio.',
    avatar: 'PR',
    time: 'Hace 3 semanas',
    avatarBg: 'bg-indigo-600'
  },
  {
    id: '4',
    author: 'Chelo Suspensión',
    rating: 5,
    text: 'Me tocó tratar con Pablo, excelente vendedor y persona. Claridad total en cada documento y las cuotas pactadas sin sorpresas.',
    avatar: 'CS',
    time: 'Hace 1 mes',
    avatarBg: 'bg-amber-600'
  },
  {
    id: '5',
    author: 'Mariana Benítez',
    rating: 5,
    text: 'Compramos en pozo en Caseros y ya nos entregaron las llaves en la fecha exacta acordada. Clamaco y Di Paolo son un 10.',
    avatar: 'MB',
    time: 'Hace 2 meses',
    avatarBg: 'bg-purple-600'
  }
];
